# Generated by Django 4.2.5 on 2023-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="author_image",
            field=models.ImageField(
                blank=True,
                default="image_authors/default.png",
                null=True,
                upload_to="image_authors/",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="book_image",
            field=models.ImageField(
                blank=True,
                default="image_books/default.png",
                null=True,
                upload_to="image_books/",
            ),
        ),
    ]
