# Generated by Django 4.2.5 on 2023-11-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_book_slug_alter_book_author_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="total_rental",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
