# Generated by Django 4.2.5 on 2023-11-24 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_book_total_rental"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="total_rental",
        ),
    ]
